// <auto-generated />
namespace DatingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _1_N_Visitors_SR : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1_N_Visitors_SR));
        
        string IMigrationMetadata.Id
        {
            get { return "202001101015041_1_N_Visitors_SR"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
