// <auto-generated />
namespace DatingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PK_Contacts_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PK_Contacts_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "202001051323539_PK_Contacts_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
